### ISSUE TITLE
No Docker

### ISSUE THREAD

**Issue by Fastidious** [WeeJeWel/wg-easy#1]
Is it possible to have it without Docker?

**Comment by WeeJeWel** [comment]
Sure, just run the node.js app in /src.

**Comment by apleschu** [comment]
1) I second the "no docker" version. Especially with systems that are connected to the internet, I prefer services that are easier audited.

2) when I try to install this with docker I get the following error message: 

andy@wireguard:~/.wg-easy$ docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Environment: Debian 10 out of the box, updated to the latest version, docker and docker-compose installed via apt

**Comment by bmullan** [comment]
@WeeJeWel Weejewei 
> Sure, just run the node.js app in /src.

Checking the /src directory I do not see any file named "**node.js**" ?

In the **src** directory or any of the other wg-easy subdirectories.

there is no "**node.js**" in your github "**src**" folder either?

Not being a node.js guy maybe I just misunderstood your statement above.

**Comment by Fastidious** [comment]
> Or did your statement mean to run $ node ./server.js

Yes.
