### ISSUE TITLE
How can I ping peers from server

### ISSUE THREAD

**Issue by aada** [WeeJeWel/wg-easy#427]
Peers can ping each other and the server. but the server can't reach peers with their addresses.
is there a way to allow the server to ping clients?

**Comment by aada** [comment]
Peers can ping each other wireguard

I tried to ping on all network interfaces ping -I "interface" 10.8.0.8but still no luck

 pinging from inside the docker container works
‘’’sudo docker exec -t -i wg-easy ping 10.8.0.8’’’

is it possible to ping from the host network?

**Comment by aada** [comment]
I Solved by routing running 
sudo route add -net 10.8.0.0/24 gw 192.168.32.2
on the the docker host

**Comment by ZevaXu** [comment]
@aada Hi, I'm having the same problem as you, I'm trying to access other nodes through the host, but ping can`t work.

I tried   
`sudo route add -net 10.0.2.3/24 gw 192.168.32.2` 
but it shows 
`route: netmask doesn't match route address`. 
the ip `10.0.2.3` is a wireguard nodes ip.

Could you please tell me how to fix it, Thank you!

**Comment by lanrat** [comment]
In addition to adding the route on the host, you need to enable nat in the container for packets arriving from the host. Otherwise the VPN clients response packets won't be routed correctly.

From within the vpn server container:
```shell
iptables -t nat -A POSTROUTING -o wg+ -j MASQUERADE
```

And set the route on the host:
```
sudo route add -net 10.8.0.0/24 gw DOCKER_CONTAINER_IP
```

Note: depending on your setup, these changes may not persist restarts of the host or container.
