### ISSUE TITLE
Clients lost after automatic docker pull command

### ISSUE THREAD

**Issue by ymurawski** [WeeJeWel/wg-easy#457]
Hi im using Ubuntu with WG-easy docker. Everything works fine but when i add a crontab to automatically pull the latest image at reboot of ubuntu all my clients lost. When i run the same command manually all clients come back.

The command is: (@reboot is just in the crontab)
@reboot sudo docker stop wg-easy ; sudo docker rm wg-easy ; sudo docker pull weejewel/wg-easy ; sudo docker run -d --name=wg-easy -e WG_HOST=XXXXXXXXXXX -e PASSWORD=XXXXXXXXX -e WG_DEFAULT_DNS="192.168.1.203, 192.168.1.1" -v ~/.wg-easy1:/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --restart unless-stopped weejewel/wg-easy

**Comment by eandersons** [comment]
That is because of volume path `~/.wg-easy` - it means that the directory `.wg-easy` should be mounted from the home directory of the user that cron job is executing as and most probably it is not the same as the user that you manually executed `docker run` with. Just provide the absolute path to the cron job command: `/home/<username>/.wg-easy`. Or use named volume.

**Comment by ymurawski** [comment]
> That is because of volume path `~/.wg-easy` - it means that the directory `.wg-easy` should be mounted from the home directory of the user that cron job is executing as and most probably it is not the same as the user that you manually executed `docker run` with. Just provide the absolute path to the cron job command: `/home/<username>/.wg-easy`. Or use named volume.

Thank you so much. It's working now 🙃
