### ISSUE TITLE
Zombie process

### ISSUE THREAD

**Issue by chenweiwen07** [WeeJeWel/wg-easy#65]
It works normally, but it produces some zombie processes. At first, there are 1 and now there are 3.
Hardware: Raspberry Pi 4B
![image](https://user-images.githubusercontent.com/35797132/132477054-3f307e43-0e0c-49e6-9cbc-3cdc7a00967f.png)
![image](https://user-images.githubusercontent.com/35797132/132475580-1fd47670-c171-443f-8893-e10e70d44863.png)
![image](https://user-images.githubusercontent.com/35797132/132475840-ab11a172-58b8-4769-ad44-17f851772615.png)

**Comment by gaby** [comment]
This also happens on debian x86 systems.

**Comment by gaby** [comment]
This is related to Docker a PID 1, it's fixable using an init

More information here: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

As you can see here using `dumb-init` solves the issue.
![image](https://user-images.githubusercontent.com/835733/133534895-6856ac18-3260-457d-9e09-7a4798b0ee00.png)

I'm going to submit a PR to fix this.

**Comment by WeeJeWel** [comment]
I'm trying to understand this issue.

When do these zombie processes get created?

**Comment by gaby** [comment]
@WeeJeWel This is happening because `wg-easy` is in the Util.js is not killing the child_process it creates every time `wg-quick` is executed.

The nodejs team also recommends not running Node as PID 1. Which is fixed by #71 More details here: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
